# API do Discord.
token: "00000000000000000000000000000000000000000000000000000000000"
client_id: 000000000000000000
prefix: "!"

# Nome do cargo para cada permissão, os canais DEVEM EXISTIR.
# developer -> Pode manipular logs para debug, reiniciar e desligar o bot.
# admin -> Pode banir usuários.
# moderator -> Pode kickar usuários.
# colaborator -> Pode manipular tickets.
developer: "dev"
admin: "admin"
moderator: "mod"
colaborator: "trusted"

# Ferramentas administrativas.
# As duas opções podem ser direcionadas para o mesmo ID.
admin_channel_id: 000000000000000000
join_part_channel_id: 000000000000000000

# Mantêm PMs em /data/logs/PM.log.
# A primeira opção mantêm log de TODAS as mensagens.
log_server_messages: false
log_private_messages: true

# Transparência.
# Exibe um relatório após banimentos e expulsões.
transparency: true
transparency_channel_id: 000000000000000000
